#!/usr/bin/env zsh

script_inlude_dir=${HOME}/.scripts

import_script() {
    if [ $# -ne 1 ]; then
        echo "usage: import <script name>" >&2
        return 1
    fi
    local script_name=$1
    local extension="${script_name##*.}"
    if [ "${extension}" = ${script_name} ]; then
        local script_name="${script_name}.sh"
    elif [ "${extension}" != "sh" ]; then
        echo "include only accepts .sh files. But you provide ${extension} extension" >&2
        return 1
    fi
    local script_name="${script_inlude_dir}/${script_name}"
    if [ ! -e "${script_name}" ]; then
        echo "Script ${script_name} does not exists." >&2
        return 1
    fi
    source ${script_name}
}

export -f import_script > /dev/null

