#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use File::Spec;

my $fzy_repo = File::Spec->catdir($FindBin::Bin, 'fzf');

unless ( -e -r -d $fzy_repo) {
    die 'Could not found directory ' . $fzy_repo . "\n";
}

chdir $fzy_repo;
unless ( system "./install " . "--key-bindings " . "--completion " . "--update-rc" ) {
    print "fuzzy successfully installed\n";
} else {
    die "could not install fuzzy \n";
}
